export * from "./footer";
export * from "./header";
export * from "./sideMenu";
export * from "./carousel";
export * from "./productCollection";
export * from "./covidMap";
export * from "./productIntro"
export * from "./productComments";
export * from "./filter";
export * from "./productList";
export * from "./register&signIn"
export * from "./paymentCard"
export * from "./checkOutCard"
export * from "./paymentForm"